//
//  AppSettings.swift
//  Paste
//
//  Typed accessors for app preferences (UserDefaults).
//

import Foundation
import AppKit

enum AppSettings {

    // MARK: - Keys

    enum Key {
        // Existing keys (keep for backward compatibility)
        static let maxItems = "maxItems"
        static let excludedApps = "excludedApps"
        static let recordImages = "recordImages"
        static let launchAtLogin = "launchAtLogin"
        static let hotKeyKeyCode = "hotKeyKeyCode"
        static let hotKeyModifiers = "hotKeyModifiers"

        // New keys (screenshot features)
        static let directPasteEnabled = "directPasteEnabled"
        static let pastePlainTextByDefault = "pastePlainTextByDefault"
        static let linkPreviewEnabled = "linkPreviewEnabled"
        static let soundEnabled = "soundEnabled"
        static let showMenuBarIcon = "showMenuBarIcon"
        static let voiceOverAnnounceEnabled = "voiceOverAnnounceEnabled"

        static let retentionPreset = "retentionPreset"
        static let retentionMaxItems = "retentionMaxItems"

        static let quickPasteModifier = "quickPasteModifier"
        static let plainTextModifier = "plainTextModifier"

        static let ignoreSensitiveContent = "ignoreSensitiveContent"
        static let ignoreAutoGeneratedContent = "ignoreAutoGeneratedContent"

        static let iCloudSyncEnabled = "iCloudSyncEnabled"

        static let hotKeyPasteKeyCode = "hotKeyPasteKeyCode"
        static let hotKeyPasteModifiers = "hotKeyPasteModifiers"
        static let hotKeyPasteEnabled = "hotKeyPasteEnabled"
        static let hotKeyPasteStackKeyCode = "hotKeyPasteStackKeyCode"
        static let hotKeyPasteStackModifiers = "hotKeyPasteStackModifiers"
        static let hotKeyPasteStackEnabled = "hotKeyPasteStackEnabled"
        static let hotKeyNextPinboardKeyCode = "hotKeyNextPinboardKeyCode"
        static let hotKeyNextPinboardModifiers = "hotKeyNextPinboardModifiers"
        static let hotKeyNextPinboardEnabled = "hotKeyNextPinboardEnabled"
        static let hotKeyPrevPinboardKeyCode = "hotKeyPrevPinboardKeyCode"
        static let hotKeyPrevPinboardModifiers = "hotKeyPrevPinboardModifiers"
        static let hotKeyPrevPinboardEnabled = "hotKeyPrevPinboardEnabled"

        static let lastPinboardIndex = "lastPinboardIndex"
        static let pinboardCount = "pinboardCount"

        static let appearance = "appearance"
        static let hasRequestedAccessibilityPermission = "hasRequestedAccessibilityPermission"

        /// Last selected filter tab: 0=All, 1=Text, 2=Image, 3=File, 4=Regex.
        static let lastSelectedFilterType = "lastSelectedFilterType"

        /// Panel display position: 0=Bottom, 1=Top, 2=Left, 3=Right.
        static let panelPosition = "panelPosition"
    }

    // MARK: - Panel Position

    enum PanelPosition: Int, CaseIterable {
        case bottom = 0
        case top = 1
        case left = 2
        case right = 3
    }

    static var panelPosition: PanelPosition {
        get {
            PanelPosition(rawValue: int(Key.panelPosition, default: PanelPosition.bottom.rawValue)) ?? .bottom
        }
        set { write(newValue.rawValue, forKey: Key.panelPosition) }
    }

    // MARK: - Appearance

    enum Appearance: Int, CaseIterable {
        case system = 0
        case light = 1
        case dark = 2
    }

    // MARK: - Helpers

    private static let defaults = UserDefaults.standard

    /// Posted (on the main thread) after any setting is written; `userInfo["key"]` is the key.
    static let didChange = Notification.Name("AppSettings.didChange")

    /// Single write path for all settings so observers get one consistent change signal.
    private static func write(_ value: Any?, forKey key: String) {
        defaults.set(value, forKey: key)
        if Thread.isMainThread {
            NotificationCenter.default.post(name: didChange, object: nil, userInfo: ["key": key])
        } else {
            DispatchQueue.main.async {
                NotificationCenter.default.post(name: didChange, object: nil, userInfo: ["key": key])
            }
        }
    }

    private static func bool(_ key: String, default defaultValue: Bool) -> Bool {
        if defaults.object(forKey: key) == nil { return defaultValue }
        return defaults.bool(forKey: key)
    }

    private static func int(_ key: String, default defaultValue: Int) -> Int {
        defaults.object(forKey: key) as? Int ?? defaultValue
    }

    private static func uint32(_ key: String, default defaultValue: UInt32) -> UInt32 {
        defaults.object(forKey: key) as? UInt32 ?? defaultValue
    }

    private static func modifierFlags(_ key: String, default defaultValue: NSEvent.ModifierFlags) -> NSEvent.ModifierFlags {
        let raw = defaults.object(forKey: key) as? UInt ?? defaultValue.rawValue
        return NSEvent.ModifierFlags(rawValue: raw)
    }

    // MARK: - Existing

    static var maxItems: Int {
        get { int(Key.maxItems, default: Constants.defaultMaxItems) }
        set { write(newValue, forKey: Key.maxItems) }
    }

    static var excludedApps: [String] {
        get { defaults.stringArray(forKey: Key.excludedApps) ?? [] }
        set { write(newValue, forKey: Key.excludedApps) }
    }

    static var recordImages: Bool {
        get { bool(Key.recordImages, default: true) }
        set { write(newValue, forKey: Key.recordImages) }
    }

    static var launchAtLogin: Bool {
        get { bool(Key.launchAtLogin, default: false) }
        set { write(newValue, forKey: Key.launchAtLogin) }
    }

    /// Legacy single hotkey (kept for compatibility; will be superseded by multi-hotkey).
    static var legacyHotKeyKeyCode: UInt32 {
        get { uint32(Key.hotKeyKeyCode, default: Constants.defaultHotKeyKeyCode) }
        set { write(newValue, forKey: Key.hotKeyKeyCode) }
    }

    /// Legacy single hotkey (kept for compatibility; will be superseded by multi-hotkey).
    static var legacyHotKeyModifiers: UInt32 {
        get { uint32(Key.hotKeyModifiers, default: Constants.defaultHotKeyModifiers) }
        set { write(newValue, forKey: Key.hotKeyModifiers) }
    }

    // MARK: - General

    static var directPasteEnabled: Bool {
        get { bool(Key.directPasteEnabled, default: true) }
        set { write(newValue, forKey: Key.directPasteEnabled) }
    }

    static var pastePlainTextByDefault: Bool {
        get { bool(Key.pastePlainTextByDefault, default: false) }
        set { write(newValue, forKey: Key.pastePlainTextByDefault) }
    }

    static var linkPreviewEnabled: Bool {
        get { bool(Key.linkPreviewEnabled, default: true) }
        set { write(newValue, forKey: Key.linkPreviewEnabled) }
    }

    static var soundEnabled: Bool {
        get { bool(Key.soundEnabled, default: true) }
        set { write(newValue, forKey: Key.soundEnabled) }
    }

    static var showMenuBarIcon: Bool {
        get { bool(Key.showMenuBarIcon, default: true) }
        set { write(newValue, forKey: Key.showMenuBarIcon) }
    }

    static var voiceOverAnnounceEnabled: Bool {
        get { bool(Key.voiceOverAnnounceEnabled, default: true) }
        set { write(newValue, forKey: Key.voiceOverAnnounceEnabled) }
    }

    // MARK: - Retention

    enum RetentionPreset: Int, CaseIterable {
        case day = 0
        case week = 1
        case month = 2
        case year = 3
        case unlimited = 4
    }

    static var retentionPreset: RetentionPreset {
        get { RetentionPreset(rawValue: int(Key.retentionPreset, default: RetentionPreset.month.rawValue)) ?? .month }
        set { write(newValue.rawValue, forKey: Key.retentionPreset) }
    }

    /// Upper bound by count, independent from time-based retention.
    static var retentionMaxItems: Int {
        get { int(Key.retentionMaxItems, default: Constants.defaultMaxItems) }
        set { write(newValue, forKey: Key.retentionMaxItems) }
    }

    // MARK: - In-panel modifiers

    static var quickPasteModifier: NSEvent.ModifierFlags {
        get { modifierFlags(Key.quickPasteModifier, default: .command) }
        set { write(newValue.rawValue, forKey: Key.quickPasteModifier) }
    }

    static var plainTextModifier: NSEvent.ModifierFlags {
        get { modifierFlags(Key.plainTextModifier, default: .shift) }
        set { write(newValue.rawValue, forKey: Key.plainTextModifier) }
    }

    // MARK: - Rules

    static var ignoreSensitiveContent: Bool {
        get { bool(Key.ignoreSensitiveContent, default: true) }
        set { write(newValue, forKey: Key.ignoreSensitiveContent) }
    }

    static var ignoreAutoGeneratedContent: Bool {
        get { bool(Key.ignoreAutoGeneratedContent, default: true) }
        set { write(newValue, forKey: Key.ignoreAutoGeneratedContent) }
    }

    // MARK: - Sync

    static var iCloudSyncEnabled: Bool {
        get { bool(Key.iCloudSyncEnabled, default: false) }
        set { write(newValue, forKey: Key.iCloudSyncEnabled) }
    }

    // MARK: - Filter Tab Names

    private static let filterTabNamePrefix = "filterTabName_"

    static func filterTabName(for type: ClipboardItemType?) -> String? {
        let suffix: String
        switch type {
        case nil:     suffix = "all"
        case .text:   suffix = "text"
        case .image:  suffix = "image"
        case .file:   suffix = "file"
        case .some:   suffix = "unknown"
        }
        return defaults.string(forKey: "\(filterTabNamePrefix)\(suffix)")
    }

    static func setFilterTabName(_ name: String, for type: ClipboardItemType?) {
        let suffix: String
        switch type {
        case nil:     suffix = "all"
        case .text:   suffix = "text"
        case .image:  suffix = "image"
        case .file:   suffix = "file"
        case .some:   suffix = "unknown"
        }
        let key = "\(filterTabNamePrefix)\(suffix)"
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty {
            defaults.removeObject(forKey: key)
        } else {
            write(trimmed, forKey: key)
        }
    }

    // MARK: - Pinboard
    
    static let pinboardCountMax = 10
    static let pinboardCountDefault = 1

    static var pinboardCount: Int {
        get { max(pinboardCountDefault, min(int(Key.pinboardCount, default: pinboardCountDefault), pinboardCountMax)) }
        set {
            write(max(pinboardCountDefault, min(newValue, pinboardCountMax)), forKey: Key.pinboardCount)
            savePinboardsToKVS()
        }
    }

    static func pinboardName(at index: Int) -> String {
        defaults.string(forKey: "pinboardName_\(index)")
            ?? String(format: String(localized: "mainpanel.pinboard.titleFormat"), index + 1)
    }

    static func setPinboardName(_ name: String, at index: Int) {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty {
            defaults.removeObject(forKey: "pinboardName_\(index)")
        } else {
            write(trimmed, forKey: "pinboardName_\(index)")
        }
        savePinboardsToKVS()
    }

    static var lastPinboardIndex: Int {
        get {
            let value = int(Key.lastPinboardIndex, default: 0)
            return max(0, min(value, pinboardCount - 1))
        }
        set {
            write(max(0, min(newValue, pinboardCount - 1)), forKey: Key.lastPinboardIndex)
        }
    }

    /// Whether the Accessibility permission dialog has been shown (prompted once per install).
    static var hasRequestedAccessibilityPermission: Bool {
        get { bool(Key.hasRequestedAccessibilityPermission, default: false) }
        set { write(newValue, forKey: Key.hasRequestedAccessibilityPermission) }
    }

    /// Last selected filter tab index: 0=All, 1=Text, 2=Image, 3=File, 4=Regex.
    static var lastSelectedFilterType: Int {
        get { max(0, min(4, int(Key.lastSelectedFilterType, default: 0))) }
        set { write(max(0, min(4, newValue)), forKey: Key.lastSelectedFilterType) }
    }

    static var appearance: Appearance {
        get { Appearance(rawValue: int(Key.appearance, default: Appearance.system.rawValue)) ?? .system }
        set {
            write(newValue.rawValue, forKey: Key.appearance)
            DispatchQueue.main.async {
                switch newValue {
                case .system: NSApp.appearance = nil
                case .light: NSApp.appearance = NSAppearance(named: .aqua)
                case .dark: NSApp.appearance = NSAppearance(named: .darkAqua)
                }
            }
        }
    }

    // MARK: - Multi-hotkey storage (to be wired in HotKeyManager)

    static var hotKeyPasteKeyCode: UInt32 {
        get { uint32(Key.hotKeyPasteKeyCode, default: Constants.defaultHotKeyKeyCode) }
        set { write(newValue, forKey: Key.hotKeyPasteKeyCode) }
    }

    static var hotKeyPasteModifiers: UInt32 {
        get { uint32(Key.hotKeyPasteModifiers, default: Constants.defaultHotKeyModifiers) }
        set { write(newValue, forKey: Key.hotKeyPasteModifiers) }
    }

    static var hotKeyPasteEnabled: Bool {
        get { bool(Key.hotKeyPasteEnabled, default: true) }
        set { write(newValue, forKey: Key.hotKeyPasteEnabled) }
    }

    static var hotKeyPasteStackKeyCode: UInt32 {
        get { uint32(Key.hotKeyPasteStackKeyCode, default: 8 /* C */) }
        set { write(newValue, forKey: Key.hotKeyPasteStackKeyCode) }
    }

    static var hotKeyPasteStackModifiers: UInt32 {
        get { uint32(Key.hotKeyPasteStackModifiers, default: Constants.defaultHotKeyModifiers) }
        set { write(newValue, forKey: Key.hotKeyPasteStackModifiers) }
    }

    static var hotKeyPasteStackEnabled: Bool {
        get { bool(Key.hotKeyPasteStackEnabled, default: true) }
        set { write(newValue, forKey: Key.hotKeyPasteStackEnabled) }
    }

    static var hotKeyNextPinboardKeyCode: UInt32 {
        get { uint32(Key.hotKeyNextPinboardKeyCode, default: 30 /* ] */) }
        set { write(newValue, forKey: Key.hotKeyNextPinboardKeyCode) }
    }

    static var hotKeyNextPinboardModifiers: UInt32 {
        get { uint32(Key.hotKeyNextPinboardModifiers, default: UInt32(NSEvent.ModifierFlags.command.rawValue)) }
        set { write(newValue, forKey: Key.hotKeyNextPinboardModifiers) }
    }

    static var hotKeyNextPinboardEnabled: Bool {
        get { bool(Key.hotKeyNextPinboardEnabled, default: true) }
        set { write(newValue, forKey: Key.hotKeyNextPinboardEnabled) }
    }

    static var hotKeyPrevPinboardKeyCode: UInt32 {
        get { uint32(Key.hotKeyPrevPinboardKeyCode, default: 33 /* [ */) }
        set { write(newValue, forKey: Key.hotKeyPrevPinboardKeyCode) }
    }

    static var hotKeyPrevPinboardModifiers: UInt32 {
        get { uint32(Key.hotKeyPrevPinboardModifiers, default: UInt32(NSEvent.ModifierFlags.command.rawValue)) }
        set { write(newValue, forKey: Key.hotKeyPrevPinboardModifiers) }
    }

    static var hotKeyPrevPinboardEnabled: Bool {
        get { bool(Key.hotKeyPrevPinboardEnabled, default: true) }
        set { write(newValue, forKey: Key.hotKeyPrevPinboardEnabled) }
    }

    // MARK: - Pinboard Sync (iCloud KV Store)

    private static let pinboardKVKey = "pinboardSettings"

    static func savePinboardsToKVS() {
        var names: [String] = []
        var colors: [String] = []
        for i in 0..<pinboardCount {
            names.append(defaults.string(forKey: "pinboardName_\(i)") ?? "")
            colors.append(defaults.string(forKey: "pinboardColor_\(i)") ?? "")
        }
        let payload: [String: Any] = ["count": pinboardCount, "names": names, "colors": colors]
        if let data = try? JSONSerialization.data(withJSONObject: payload) {
            kvStore.set(data, forKey: pinboardKVKey)
            kvStore.synchronize()
        }
    }

    static func loadPinboardsFromKVS() {
        guard let data = kvStore.data(forKey: pinboardKVKey),
              let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let count = dict["count"] as? Int else { return }
        let names = dict["names"] as? [String] ?? []
        let colors = dict["colors"] as? [String] ?? []
        let newCount = max(pinboardCountDefault, min(count, pinboardCountMax))
        write(newCount, forKey: Key.pinboardCount)
        for i in 0..<newCount {
            if i < names.count && !names[i].isEmpty {
                write(names[i], forKey: "pinboardName_\(i)")
            }
            if i < colors.count && !colors[i].isEmpty {
                write(colors[i], forKey: "pinboardColor_\(i)")
            }
        }
    }

    // MARK: - Custom Types (iCloud KV Store, syncs with iOS)

    private static let customTypesKVKey = "customTypes"
    private static let kvStore = NSUbiquitousKeyValueStore.default

    /// Loads the current custom type list from iCloud KV Store.
    static var customTypes: [CustomType] {
        get {
            guard let data = kvStore.data(forKey: customTypesKVKey) else { return [] }
            return (try? JSONDecoder().decode([CustomType].self, from: data)) ?? []
        }
        set {
            if let data = try? JSONEncoder().encode(newValue) {
                kvStore.set(data, forKey: customTypesKVKey)
                kvStore.synchronize()
            }
        }
    }

    /// Creates a new custom type with the given name and returns it.
    @discardableResult
    static func addCustomType(name: String) -> CustomType {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        let newType = CustomType(name: trimmed.isEmpty ? "Custom" : trimmed)
        var list = customTypes
        list.append(newType)
        customTypes = list
        return newType
    }

    /// Removes the custom type with the given id.
    static func removeCustomType(id: String) {
        customTypes = customTypes.filter { $0.id != id }
    }

    /// Renames the custom type with the given id.
    static func renameCustomType(id: String, name: String) {
        var list = customTypes
        guard let idx = list.firstIndex(where: { $0.id == id }) else { return }
        list[idx].name = name.trimmingCharacters(in: .whitespacesAndNewlines)
        customTypes = list
    }
}

