//
//  PreferencesViewModel.swift
//  Paste
//
//  Preferences ViewModel
//

import Foundation
import ServiceManagement
import AppKit
import CloudKit
import ApplicationServices

@MainActor
class PreferencesViewModel: ObservableObject {
    
    // MARK: - Published Properties
    
    @Published var maxItems: Int {
        didSet {
            AppSettings.maxItems = maxItems
        }
    }
    
    @Published var recordImages: Bool {
        didSet {
            AppSettings.recordImages = recordImages
        }
    }
    
    @Published var launchAtLogin: Bool {
        didSet {
            setLaunchAtLogin(launchAtLogin)
        }
    }
    
    @Published var excludedApps: [ExcludedApp] = []

    // MARK: - General (screenshot)
    
    @Published var directPasteEnabled: Bool {
        didSet {
            if directPasteEnabled && !PermissionChecker.hasAccessibilityPermission {
                PermissionChecker.requestWithSystemPrompt()
                DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { [weak self] in
                    if !PermissionChecker.hasAccessibilityPermission {
                        self?.directPasteEnabled = false
                    }
                }
            }
            AppSettings.directPasteEnabled = directPasteEnabled
        }
    }

    @Published var voiceOverAnnounceEnabled: Bool {
        didSet { AppSettings.voiceOverAnnounceEnabled = voiceOverAnnounceEnabled }
    }
    
    @Published var pastePlainTextByDefault: Bool {
        didSet { AppSettings.pastePlainTextByDefault = pastePlainTextByDefault }
    }
    
    @Published var linkPreviewEnabled: Bool {
        didSet { AppSettings.linkPreviewEnabled = linkPreviewEnabled }
    }
    
    @Published var soundEnabled: Bool {
        didSet { AppSettings.soundEnabled = soundEnabled }
    }
    
    @Published var showMenuBarIcon: Bool {
        didSet { AppSettings.showMenuBarIcon = showMenuBarIcon }
    }
    
    @Published var appearance: AppSettings.Appearance {
        didSet { AppSettings.appearance = appearance }
    }

    @Published var panelPosition: AppSettings.PanelPosition {
        didSet { AppSettings.panelPosition = panelPosition }
    }

    // MARK: - Retention (time + count)
    
    @Published var retentionPreset: AppSettings.RetentionPreset {
        didSet { AppSettings.retentionPreset = retentionPreset }
    }
    
    @Published var retentionMaxItems: Int {
        didSet { AppSettings.retentionMaxItems = retentionMaxItems }
    }
    
    // MARK: - Sync
    
    @Published var iCloudSyncEnabled: Bool {
        didSet {
            AppSettings.iCloudSyncEnabled = iCloudSyncEnabled
            // Switching requires restarting CoreData stack (best-effort message).
            iCloudStatusMessage = String(localized: "preferences.sync.restartToApply")
            refreshICloudStatus()
        }
    }
    
    @Published var iCloudStatusMessage: String = ""
    @Published var isICloudCapabilitySupported: Bool = false
    @Published var isSyncing: Bool = false
    @Published var syncFeedbackMessage: String?
    
    // MARK: - In-panel modifiers
    
    @Published var quickPasteModifier: NSEvent.ModifierFlags {
        didSet { AppSettings.quickPasteModifier = quickPasteModifier }
    }
    
    @Published var plainTextModifier: NSEvent.ModifierFlags {
        didSet { AppSettings.plainTextModifier = plainTextModifier }
    }

    // MARK: - Rules
    
    @Published var ignoreSensitiveContent: Bool {
        didSet { AppSettings.ignoreSensitiveContent = ignoreSensitiveContent }
    }
    
    @Published var ignoreAutoGeneratedContent: Bool {
        didSet { AppSettings.ignoreAutoGeneratedContent = ignoreAutoGeneratedContent }
    }
    
    @Published var hotKeyPaste: HotKeyBinding {
        didSet { persistAndApplyHotKey(.paste, hotKeyPaste) }
    }
    
    @Published var hotKeyPasteStack: HotKeyBinding {
        didSet { persistAndApplyHotKey(.pasteStack, hotKeyPasteStack) }
    }
    
    @Published var hotKeyNextPinboard: HotKeyBinding {
        didSet { persistAndApplyHotKey(.nextPinboard, hotKeyNextPinboard) }
    }
    
    @Published var hotKeyPrevPinboard: HotKeyBinding {
        didSet { persistAndApplyHotKey(.previousPinboard, hotKeyPrevPinboard) }
    }
    
    // MARK: - Initialization
    
    init() {
        self.maxItems = AppSettings.maxItems
        self.recordImages = AppSettings.recordImages
        self.launchAtLogin = AppSettings.launchAtLogin
        
        self.directPasteEnabled = AppSettings.directPasteEnabled
        self.voiceOverAnnounceEnabled = AppSettings.voiceOverAnnounceEnabled
        self.pastePlainTextByDefault = AppSettings.pastePlainTextByDefault
        self.linkPreviewEnabled = AppSettings.linkPreviewEnabled
        self.soundEnabled = AppSettings.soundEnabled
        self.showMenuBarIcon = AppSettings.showMenuBarIcon
        self.appearance = AppSettings.appearance
        self.panelPosition = AppSettings.panelPosition
        self.quickPasteModifier = AppSettings.quickPasteModifier
        self.plainTextModifier = AppSettings.plainTextModifier
        self.ignoreSensitiveContent = AppSettings.ignoreSensitiveContent
        self.ignoreAutoGeneratedContent = AppSettings.ignoreAutoGeneratedContent
        self.retentionPreset = AppSettings.retentionPreset
        self.retentionMaxItems = AppSettings.retentionMaxItems
        self.iCloudSyncEnabled = AppSettings.iCloudSyncEnabled
        
        self.hotKeyPaste = HotKeyBinding(
            enabled: AppSettings.hotKeyPasteEnabled,
            keyCode: AppSettings.hotKeyPasteKeyCode,
            modifiers: AppSettings.hotKeyPasteModifiers
        )
        self.hotKeyPasteStack = HotKeyBinding(
            enabled: AppSettings.hotKeyPasteStackEnabled,
            keyCode: AppSettings.hotKeyPasteStackKeyCode,
            modifiers: AppSettings.hotKeyPasteStackModifiers
        )
        self.hotKeyNextPinboard = HotKeyBinding(
            enabled: AppSettings.hotKeyNextPinboardEnabled,
            keyCode: AppSettings.hotKeyNextPinboardKeyCode,
            modifiers: AppSettings.hotKeyNextPinboardModifiers
        )
        self.hotKeyPrevPinboard = HotKeyBinding(
            enabled: AppSettings.hotKeyPrevPinboardEnabled,
            keyCode: AppSettings.hotKeyPrevPinboardKeyCode,
            modifiers: AppSettings.hotKeyPrevPinboardModifiers
        )
        
        loadExcludedApps()
        // HotKeyManager registration is owned by AppDelegate. Here we only persist/update.
        self.isICloudCapabilitySupported = ICloudCapability.isSupportedBySigning()
        refreshICloudStatus()
    }
    
    // MARK: - Excluded Apps
    
    func loadExcludedApps() {
        let bundleIds = AppSettings.excludedApps
        excludedApps = bundleIds.compactMap { bundleId in
            guard let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleId) else {
                return ExcludedApp(bundleId: bundleId, name: bundleId, icon: nil)
            }
            let name = FileManager.default.displayName(atPath: url.path)
            let icon = NSWorkspace.shared.icon(forFile: url.path)
            return ExcludedApp(bundleId: bundleId, name: name, icon: icon)
        }
    }
    
    func addExcludedApp() {
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.application]
        panel.directoryURL = URL(fileURLWithPath: "/Applications")
        panel.allowsMultipleSelection = false
        
        if panel.runModal() == .OK, let url = panel.url {
            if let bundle = Bundle(url: url), let bundleId = bundle.bundleIdentifier {
                addExcludedApp(bundleId: bundleId)
            }
        }
    }
    
    func addExcludedApp(bundleId: String) {
        var bundleIds = AppSettings.excludedApps
        guard !bundleIds.contains(bundleId) else { return }
        
        bundleIds.append(bundleId)
        AppSettings.excludedApps = bundleIds
        loadExcludedApps()
    }
    
    func removeExcludedApp(_ app: ExcludedApp) {
        var bundleIds = AppSettings.excludedApps
        bundleIds.removeAll { $0 == app.bundleId }
        AppSettings.excludedApps = bundleIds
        loadExcludedApps()
    }
    
    // MARK: - Launch at Login
    
    private func setLaunchAtLogin(_ enabled: Bool) {
        if #available(macOS 13.0, *) {
            do {
                if enabled {
                    try SMAppService.mainApp.register()
                } else {
                    try SMAppService.mainApp.unregister()
                }
                AppSettings.launchAtLogin = enabled
            } catch {
                print("Failed to set launch-at-login: \(error)")
            }
        }
    }
    
    // MARK: - Hot Key (multi)
    
    func resetHotKeysToDefault() {
        hotKeyPaste = HotKeyBinding(enabled: true, keyCode: Constants.defaultHotKeyKeyCode, modifiers: Constants.defaultHotKeyModifiers)
        hotKeyPasteStack = HotKeyBinding(enabled: true, keyCode: 8, modifiers: Constants.defaultHotKeyModifiers) // C
        hotKeyNextPinboard = HotKeyBinding(enabled: true, keyCode: 30, modifiers: UInt32(NSEvent.ModifierFlags.command.rawValue)) // ⌘]
        hotKeyPrevPinboard = HotKeyBinding(enabled: true, keyCode: 33, modifiers: UInt32(NSEvent.ModifierFlags.command.rawValue)) // ⌘[
    }
    
    private func persistAndApplyHotKey(_ action: HotKeyManager.HotKeyAction, _ binding: HotKeyBinding) {
        // Save
        switch action {
        case .paste:
            AppSettings.hotKeyPasteEnabled = binding.enabled
            AppSettings.hotKeyPasteKeyCode = binding.keyCode
            AppSettings.hotKeyPasteModifiers = binding.modifiers
        case .pasteStack:
            AppSettings.hotKeyPasteStackEnabled = binding.enabled
            AppSettings.hotKeyPasteStackKeyCode = binding.keyCode
            AppSettings.hotKeyPasteStackModifiers = binding.modifiers
        case .nextPinboard:
            AppSettings.hotKeyNextPinboardEnabled = binding.enabled
            AppSettings.hotKeyNextPinboardKeyCode = binding.keyCode
            AppSettings.hotKeyNextPinboardModifiers = binding.modifiers
        case .previousPinboard:
            AppSettings.hotKeyPrevPinboardEnabled = binding.enabled
            AppSettings.hotKeyPrevPinboardKeyCode = binding.keyCode
            AppSettings.hotKeyPrevPinboardModifiers = binding.modifiers
        }
        
        // Apply immediately (handler is already set by AppDelegate)
        HotKeyManager.shared.updateHotKey(
            action: action,
            enabled: binding.enabled,
            keyCode: binding.keyCode,
            modifiers: binding.modifiers
        )
    }
    
    // MARK: - Data Management
    
    func clearAllHistory() {
        ClipboardService.shared.deleteAllItems()
    }
    
    /// Returns the size of the CoreData SQLite database file.
    func getDatabaseSize() -> String {
        let fileManager = FileManager.default
        guard let containerURL = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask).first else {
            return String(localized: "preferences.databaseSize.unknown")
        }
        
        let storeURL = containerURL.appendingPathComponent("PasteTool.sqlite")
        
        do {
            let attributes = try fileManager.attributesOfItem(atPath: storeURL.path)
            if let size = attributes[.size] as? Int64 {
                return ByteCountFormatter.string(fromByteCount: size, countStyle: .file)
            }
        } catch {
            // File may not exist yet.
        }
        
        return String(localized: "preferences.databaseSize.zero")
    }
    
    // MARK: - Sync
    
    func refreshICloudStatus() {
        // Check iCloud entitlement support.
        if !isICloudCapabilitySupported {
            if iCloudSyncEnabled {
                iCloudSyncEnabled = false
            }
            iCloudStatusMessage = String(localized: "preferences.sync.notSupported.configuration", defaultValue: "iCloud 能力未正确配置，请检查 Xcode 项目设置和开发者账号配置")
            return
        }
        
        // Check the user's iCloud account status.
        let container = CKContainer(identifier: Constants.iCloudContainerIdentifier)
        container.accountStatus { [weak self] status, error in
            DispatchQueue.main.async {
                guard let self else { return }
                if let error {
                    self.iCloudStatusMessage = error.localizedDescription
                    return
                }
                switch status {
                case .available:
                    self.iCloudStatusMessage = String(localized: "preferences.sync.status.available")
                case .noAccount:
                    self.iCloudStatusMessage = String(localized: "preferences.sync.status.noAccount")
                case .restricted:
                    self.iCloudStatusMessage = String(localized: "preferences.sync.status.restricted")
                case .temporarilyUnavailable:
                    self.iCloudStatusMessage = String(localized: "preferences.sync.status.temporarilyUnavailable")
                case .couldNotDetermine:
                    self.iCloudStatusMessage = String(localized: "preferences.sync.status.unknown")
                @unknown default:
                    self.iCloudStatusMessage = String(localized: "preferences.sync.status.unknown")
                }
            }
        }
    }
    
    func syncNow() {
        guard !isSyncing else { return }
        isSyncing = true
        syncFeedbackMessage = nil
        
        CoreDataStack.shared.requestSyncNow { [weak self] error in
            guard let self else { return }
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
                self.isSyncing = false
                if let error {
                    self.syncFeedbackMessage = String(localized: "preferences.sync.feedback.failed", defaultValue: "Sync failed") + ": " + error.localizedDescription
                } else {
                    self.syncFeedbackMessage = String(localized: "preferences.sync.feedback.triggered", defaultValue: "Sync triggered.")
                }
                self.refreshICloudStatus()
                DispatchQueue.main.asyncAfter(deadline: .now() + 3.0) {
                    if self.syncFeedbackMessage != nil { self.syncFeedbackMessage = nil }
                }
            }
        }
    }
}

// MARK: - Supporting Types

struct ExcludedApp: Identifiable {
    let id = UUID()
    let bundleId: String
    let name: String
    let icon: NSImage?
}
