//
//  iOSAppSettings.swift
//  Paste-iOS
//

import Foundation
import Combine
import CoreData
import CloudKit

final class iOSAppSettings: ObservableObject {

    static let shared = iOSAppSettings()

    private let defaults: UserDefaults

    static let pinboardCountDefault = 1
    static let pinboardCountMax = 10

    private init() {
        let ud = UserDefaults(suiteName: "group.gxlself.paste-tool") ?? .standard
        defaults = ud

        // Kick off iCloud KV sync and load persisted custom types.
        NSUbiquitousKeyValueStore.default.synchronize()
        if let data = NSUbiquitousKeyValueStore.default.data(forKey: Self.customTypesKVKey),
           let decoded = try? JSONDecoder().decode([CustomType].self, from: data) {
            _customTypes = Published(initialValue: decoded)
        }

        // Reload custom types and pinboards when another device pushes an update.
        NotificationCenter.default.addObserver(
            forName: NSUbiquitousKeyValueStore.didChangeExternallyNotification,
            object: NSUbiquitousKeyValueStore.default,
            queue: .main
        ) { [weak self] _ in
            self?.loadCustomTypes()
            self?.loadPinboardsFromKVS()
        }

        let count = ud.integer(forKey: Keys.pinboardCount)
        _pinboardCount = Published(initialValue: count == 0 ? Self.pinboardCountDefault : min(count, Self.pinboardCountMax))
        _iCloudSyncEnabled = Published(initialValue: ud.bool(forKey: Keys.iCloudSync))
        _collectWhenActive = Published(initialValue: ud.object(forKey: Keys.collectWhenActive) as? Bool ?? true)
        _collectFromKeyboard = Published(initialValue: ud.object(forKey: Keys.collectFromKeyboard) as? Bool ?? true)
        _recordImages = Published(initialValue: ud.object(forKey: Keys.recordImages) as? Bool ?? true)
        _ignoreSensitiveContent = Published(initialValue: ud.object(forKey: Keys.ignoreSensitiveContent) as? Bool ?? true)
        _ignoreAutoGeneratedContent = Published(initialValue: ud.object(forKey: Keys.ignoreAutoGeneratedContent) as? Bool ?? true)
        _linkPreviewEnabled = Published(initialValue: ud.object(forKey: Keys.linkPreviewEnabled) as? Bool ?? true)
        _showInScreenSharing = Published(initialValue: ud.object(forKey: Keys.showInScreenSharing) as? Bool ?? true)
        _retentionPreset = Published(initialValue: RetentionPreset(rawValue: ud.integer(forKey: Keys.retentionPreset)) ?? .month)
        _retentionMaxItems = Published(initialValue: ud.object(forKey: Keys.retentionMaxItems) as? Int ?? 500)
    }

    // MARK: - Keys

    private enum Keys {
        static let pinboardCount = "pinboardCount"
        static let pinboardName = "pinboardName_"
        static let pinboardColor = "pinboardColor_"
        static let filterTabName = "filterTabName_"
        static let iCloudSync = "iCloudSyncEnabled"
        static let collectWhenActive = "collectWhenActive"
        static let collectFromKeyboard = "collectFromKeyboard"
        static let lastPinboardIndex = "lastPinboardIndex"
        static let recordImages = "recordImages"
        static let ignoreSensitiveContent = "ignoreSensitiveContent"
        static let ignoreAutoGeneratedContent = "ignoreAutoGeneratedContent"
        static let linkPreviewEnabled = "linkPreviewEnabled"
        static let showInScreenSharing = "showInScreenSharing"
        static let retentionPreset = "retentionPreset"
        static let retentionMaxItems = "retentionMaxItems"
    }

    // MARK: - Pinboards

    @Published var pinboardCount: Int = 5 {
        didSet {
            defaults.set(pinboardCount, forKey: Keys.pinboardCount)
            if !isSyncingFromKVS { savePinboardsToKVS() }
        }
    }

    static let pinboardColors: [String] = [
        "#FF3B30", "#FF9500", "#FFCC00", "#34C759", "#007AFF",
        "#5856D6", "#AF52DE", "#FF2D55", "#A2845E", "#8E8E93"
    ]

    func setPinboardName(_ name: String, at index: Int) {
        defaults.set(name, forKey: "\(Keys.pinboardName)\(index)")
        objectWillChange.send()
        savePinboardsToKVS()
    }

    func pinboardColorHex(at index: Int) -> String {
        defaults.string(forKey: "\(Keys.pinboardColor)\(index)")
            ?? Self.pinboardColors[index % Self.pinboardColors.count]
    }

    func setPinboardColor(_ hex: String, at index: Int) {
        defaults.set(hex, forKey: "\(Keys.pinboardColor)\(index)")
        objectWillChange.send()
        savePinboardsToKVS()
    }

    func pinboardName(at index: Int) -> String {
        defaults.string(forKey: "\(Keys.pinboardName)\(index)")
            ?? String(format: NSLocalizedString("mainpanel.pinboard.titleFormat", comment: ""), index + 1)
    }

    func addPinboard() {
        guard pinboardCount < Self.pinboardCountMax else { return }
        pinboardCount += 1
    }

    func removePinboard(at index: Int) {
        guard pinboardCount > 1 else { return }
        for i in index..<(pinboardCount - 1) {
            let nextName = pinboardName(at: i + 1)
            let nextColor = pinboardColorHex(at: i + 1)
            setPinboardName(nextName, at: i)
            setPinboardColor(nextColor, at: i)
        }
        defaults.removeObject(forKey: "\(Keys.pinboardName)\(pinboardCount - 1)")
        defaults.removeObject(forKey: "\(Keys.pinboardColor)\(pinboardCount - 1)")
        pinboardCount -= 1
    }

    func movePinboard(from source: Int, to destination: Int) {
        guard source != destination else { return }
        let srcName = pinboardName(at: source)
        let srcColor = pinboardColorHex(at: source)

        if source < destination {
            for i in source..<destination {
                setPinboardName(pinboardName(at: i + 1), at: i)
                setPinboardColor(pinboardColorHex(at: i + 1), at: i)
            }
        } else {
            for i in stride(from: source, through: destination + 1, by: -1) {
                setPinboardName(pinboardName(at: i - 1), at: i)
                setPinboardColor(pinboardColorHex(at: i - 1), at: i)
            }
        }
        setPinboardName(srcName, at: destination)
        setPinboardColor(srcColor, at: destination)
        objectWillChange.send()
    }

    // MARK: - Pinboard Sync (iCloud KV Store)

    private static let pinboardKVKey = "pinboardSettings"

    func savePinboardsToKVS() {
        var names: [String] = []
        var colors: [String] = []
        for i in 0..<pinboardCount {
            names.append(defaults.string(forKey: "\(Keys.pinboardName)\(i)") ?? "")
            colors.append(defaults.string(forKey: "\(Keys.pinboardColor)\(i)") ?? "")
        }
        let payload: [String: Any] = ["count": pinboardCount, "names": names, "colors": colors]
        if let data = try? JSONSerialization.data(withJSONObject: payload) {
            kvStore.set(data, forKey: Self.pinboardKVKey)
            kvStore.synchronize()
        }
    }

    private var isSyncingFromKVS = false

    func loadPinboardsFromKVS() {
        guard let data = kvStore.data(forKey: Self.pinboardKVKey),
              let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let count = dict["count"] as? Int else { return }
        let names = dict["names"] as? [String] ?? []
        let colors = dict["colors"] as? [String] ?? []
        let newCount = max(Self.pinboardCountDefault, min(count, Self.pinboardCountMax))
        defaults.set(newCount, forKey: Keys.pinboardCount)
        for i in 0..<newCount {
            if i < names.count && !names[i].isEmpty {
                defaults.set(names[i], forKey: "\(Keys.pinboardName)\(i)")
            }
            if i < colors.count && !colors[i].isEmpty {
                defaults.set(colors[i], forKey: "\(Keys.pinboardColor)\(i)")
            }
        }
        isSyncingFromKVS = true
        pinboardCount = newCount
        isSyncingFromKVS = false
    }

    // MARK: - Filter Tab Names

    private func filterTabKey(for type: ClipboardItemType?) -> String {
        let suffix: String
        switch type {
        case nil:     suffix = "all"
        case .text:   suffix = "text"
        case .image:  suffix = "image"
        case .file:   suffix = "file"
        case .some:   suffix = "unknown"
        }
        return "\(Keys.filterTabName)\(suffix)"
    }

    func filterTabName(for type: ClipboardItemType?) -> String? {
        defaults.string(forKey: filterTabKey(for: type))
    }

    func setFilterTabName(_ name: String, for type: ClipboardItemType?) {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty {
            defaults.removeObject(forKey: filterTabKey(for: type))
        } else {
            defaults.set(trimmed, forKey: filterTabKey(for: type))
        }
        objectWillChange.send()
    }

    // MARK: - Clear Items By Type

    func clearItems(ofType type: ClipboardItemType?) {
        let stack = SharedCoreDataStack.shared
        let ctx = stack.viewContext
        let request: NSFetchRequest<NSFetchRequestResult> = NSFetchRequest(entityName: "ClipboardItemEntity")
        if let type {
            request.predicate = NSPredicate(format: "type == %d", type.rawValue)
        }
        let batchDelete = NSBatchDeleteRequest(fetchRequest: request)
        _ = try? ctx.execute(batchDelete)
        stack.save()
    }

    // MARK: - General

    @Published var iCloudSyncEnabled: Bool = false {
        didSet { defaults.set(iCloudSyncEnabled, forKey: Keys.iCloudSync) }
    }

    /// Shown under the iCloud toggle (CloudKit account status).
    @Published var iCloudAccountStatusMessage: String = ""

    private static let cloudKitContainerID = "iCloud.gxlself.paste-tool"

    /// Refreshes `iCloudAccountStatusMessage` from CloudKit (call from Settings).
    func refreshICloudAccountStatus() {
        let container = CKContainer(identifier: Self.cloudKitContainerID)
        container.accountStatus { [weak self] status, error in
            DispatchQueue.main.async {
                guard let self else { return }
                if let error {
                    self.iCloudAccountStatusMessage = error.localizedDescription
                    return
                }
                switch status {
                case .available:
                    self.iCloudAccountStatusMessage = String(localized: "preferences.sync.status.available")
                case .noAccount:
                    self.iCloudAccountStatusMessage = String(localized: "preferences.sync.status.noAccount")
                case .restricted:
                    self.iCloudAccountStatusMessage = String(localized: "preferences.sync.status.restricted")
                case .temporarilyUnavailable:
                    self.iCloudAccountStatusMessage = String(localized: "preferences.sync.status.temporarilyUnavailable")
                case .couldNotDetermine:
                    self.iCloudAccountStatusMessage = String(localized: "preferences.sync.status.unknown")
                @unknown default:
                    self.iCloudAccountStatusMessage = String(localized: "preferences.sync.status.unknown")
                }
            }
        }
    }

    @Published var collectWhenActive: Bool = true {
        didSet { defaults.set(collectWhenActive, forKey: Keys.collectWhenActive) }
    }

    @Published var collectFromKeyboard: Bool = true {
        didSet { defaults.set(collectFromKeyboard, forKey: Keys.collectFromKeyboard) }
    }

    @Published var recordImages: Bool = true {
        didSet { defaults.set(recordImages, forKey: Keys.recordImages) }
    }

    @Published var ignoreSensitiveContent: Bool = true {
        didSet { defaults.set(ignoreSensitiveContent, forKey: Keys.ignoreSensitiveContent) }
    }

    @Published var ignoreAutoGeneratedContent: Bool = true {
        didSet { defaults.set(ignoreAutoGeneratedContent, forKey: Keys.ignoreAutoGeneratedContent) }
    }

    @Published var linkPreviewEnabled: Bool = true {
        didSet { defaults.set(linkPreviewEnabled, forKey: Keys.linkPreviewEnabled) }
    }

    @Published var showInScreenSharing: Bool = true {
        didSet { defaults.set(showInScreenSharing, forKey: Keys.showInScreenSharing) }
    }

    // MARK: - Retention

    enum RetentionPreset: Int, CaseIterable {
        case day = 0, week = 1, month = 2, year = 3, unlimited = 4
    }

    @Published var retentionPreset: RetentionPreset = .month {
        didSet { defaults.set(retentionPreset.rawValue, forKey: Keys.retentionPreset) }
    }

    @Published var retentionMaxItems: Int = 500 {
        didSet { defaults.set(retentionMaxItems, forKey: Keys.retentionMaxItems) }
    }

    var lastPinboardIndex: Int {
        get { defaults.integer(forKey: Keys.lastPinboardIndex) }
        set { defaults.set(newValue, forKey: Keys.lastPinboardIndex) }
    }

    // MARK: - Database

    func getDatabaseSize() -> String {
        let groupID = "group.gxlself.paste-tool"
        guard let groupURL = FileManager.default.containerURL(
            forSecurityApplicationGroupIdentifier: groupID
        ) else { return NSLocalizedString("preferences.databaseSize.unknown", comment: "") }

        let storeURL = groupURL.appendingPathComponent("PasteTool.sqlite")
        let suffixes = [storeURL, storeURL.appendingPathExtension("shm"), storeURL.appendingPathExtension("wal")]
        var total: Int64 = 0
        for url in suffixes {
            total += (try? FileManager.default.attributesOfItem(atPath: url.path)[.size] as? Int64) ?? 0
        }
        if total == 0 { return NSLocalizedString("preferences.databaseSize.zero", comment: "") }
        let formatter = ByteCountFormatter()
        formatter.countStyle = .file
        return formatter.string(fromByteCount: total)
    }

    func clearAllHistory() {
        let stack = SharedCoreDataStack.shared
        let ctx = stack.viewContext
        let request: NSFetchRequest<NSFetchRequestResult> = NSFetchRequest(entityName: "ClipboardItemEntity")
        let batchDelete = NSBatchDeleteRequest(fetchRequest: request)
        _ = try? ctx.execute(batchDelete)
        stack.save()
    }

    // MARK: - Custom Types (iCloud KV Store, syncs with macOS)

    private static let customTypesKVKey = "customTypes"
    private let kvStore = NSUbiquitousKeyValueStore.default

    @Published var customTypes: [CustomType] = []

    func loadCustomTypes() {
        guard let data = kvStore.data(forKey: Self.customTypesKVKey) else { customTypes = []; return }
        customTypes = (try? JSONDecoder().decode([CustomType].self, from: data)) ?? []
    }

    func saveCustomTypes() {
        if let data = try? JSONEncoder().encode(customTypes) {
            kvStore.set(data, forKey: Self.customTypesKVKey)
            kvStore.synchronize()
        }
    }

    func addCustomType(name: String) {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        customTypes.append(CustomType(name: trimmed.isEmpty ? "Custom" : trimmed))
        saveCustomTypes()
        objectWillChange.send()
    }

    func removeCustomType(id: String) {
        customTypes.removeAll { $0.id == id }
        saveCustomTypes()
        objectWillChange.send()
    }

    func renameCustomType(id: String, name: String) {
        guard let idx = customTypes.firstIndex(where: { $0.id == id }) else { return }
        customTypes[idx].name = name.trimmingCharacters(in: .whitespacesAndNewlines)
        saveCustomTypes()
        objectWillChange.send()
    }
}
