//
//  SettingsView.swift
//  Paste-iOS
//

import SwiftUI

struct SettingsView: View {

    @ObservedObject var settings: iOSAppSettings
    @Environment(\.dismiss) private var dismiss
    @State private var showClearConfirmation = false
    @State private var showPastePermissionGuide = false

    var body: some View {
        NavigationStack {
            List {
                extensionsSection
                generalSection
                clipboardSection
                rulesSection
                storageSection
                privacySection
                supportSection
                legalSection
            }
            .navigationTitle(Text("menu.action.settings"))
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button {
                        dismiss()
                    } label: {
                        Image(systemName: "xmark")
                            .font(.body.weight(.medium))
                            .foregroundStyle(.secondary)
                    }
                }
            }
            .sheet(isPresented: $showPastePermissionGuide) {
                PastePermissionGuideView()
            }
            .confirmationDialog(
                Text("preferences.general.clearConfirm.title"),
                isPresented: $showClearConfirmation,
                titleVisibility: .visible
            ) {
                Button(String(localized: "preferences.general.clearConfirm.confirm"), role: .destructive) {
                    settings.clearAllHistory()
                }
                Button(String(localized: "preferences.general.clearConfirm.cancel"), role: .cancel) {}
            } message: {
                Text("preferences.general.clearConfirm.message")
            }
        }
    }

    // MARK: - Extensions

    private var extensionsSection: some View {
        Section {
            NavigationLink {
                keyboardSettingsDetail
            } label: {
                Label {
                    Text("preferences.tab.shortcuts")
                } icon: {
                    SettingsIcon(systemName: "keyboard", color: .blue)
                }
            }

            NavigationLink {
                actionExtensionDetail
            } label: {
                Label {
                    Text("preferences.general.integration")
                } icon: {
                    SettingsIcon(systemName: "square.and.arrow.up", color: .green)
                }
            }
        }
    }

    // MARK: - General (iCloud)

    private var generalSection: some View {
        Section(header: Text("preferences.tab.general")) {
            Toggle(isOn: $settings.iCloudSyncEnabled) {
                VStack(alignment: .leading, spacing: 2) {
                    Text("preferences.sync.enableICloud")
                    if settings.iCloudSyncEnabled {
                        Text("preferences.sync.restartToApply")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            }
        }
    }

    // MARK: - Clipboard collection

    private var clipboardSection: some View {
        Section(header: Text("ios.settings.clipboardCollection")) {
            Toggle(String(localized: "ios.settings.collectWhenActive"), isOn: $settings.collectWhenActive)
            Toggle(String(localized: "ios.settings.collectFromKeyboard"), isOn: $settings.collectFromKeyboard)
            Toggle(String(localized: "preferences.general.recordImages"), isOn: $settings.recordImages)
            Toggle(String(localized: "preferences.general.linkPreview"), isOn: $settings.linkPreviewEnabled)

            Button {
                showPastePermissionGuide = true
            } label: {
                HStack {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("ios.pastePermission.settingsToggle")
                            .foregroundStyle(Color(UIColor.label))
                        Text("ios.pastePermission.settingsToggle.desc")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    Spacer()
                    Image(systemName: "info.circle")
                        .foregroundStyle(Color.accentColor)
                }
            }
        }
    }

    // MARK: - Rules

    private var rulesSection: some View {
        Section(header: Text("preferences.tab.rules")) {
            Toggle(String(localized: "preferences.rules.ignoreSensitive"), isOn: $settings.ignoreSensitiveContent)
            Toggle(String(localized: "preferences.rules.ignoreAutoGenerated"), isOn: $settings.ignoreAutoGeneratedContent)
        }
    }

    // MARK: - Storage

    private var storageSection: some View {
        Section(header: Text("preferences.general.storage")) {
            retentionPicker

            if settings.retentionPreset != .unlimited {
                HStack {
                    Text("preferences.general.maxItems")
                    Spacer()
                    Stepper("\(settings.retentionMaxItems)", value: $settings.retentionMaxItems, in: 50...10000, step: 50)
                        .fixedSize()
                }
            }

            HStack {
                Text("preferences.general.databaseSize")
                Spacer()
                Text(settings.getDatabaseSize())
                    .foregroundStyle(.secondary)
            }

            Button(role: .destructive) {
                showClearConfirmation = true
            } label: {
                Text("preferences.general.clearAllHistory")
            }
        }
    }

    private var retentionPicker: some View {
        HStack {
            Text("preferences.general.retentionCapacity")
            Spacer()
            Picker("", selection: $settings.retentionPreset) {
                Text("preferences.general.retention.day").tag(iOSAppSettings.RetentionPreset.day)
                Text("preferences.general.retention.week").tag(iOSAppSettings.RetentionPreset.week)
                Text("preferences.general.retention.month").tag(iOSAppSettings.RetentionPreset.month)
                Text("preferences.general.retention.year").tag(iOSAppSettings.RetentionPreset.year)
                Text("preferences.general.retention.unlimited").tag(iOSAppSettings.RetentionPreset.unlimited)
            }
            .labelsHidden()
            .pickerStyle(.menu)
        }
    }

    // MARK: - Privacy

    private var privacySection: some View {
        Section(header: Text("ios.settings.privacy")) {
            Toggle(String(localized: "ios.settings.showInScreenSharing"), isOn: $settings.showInScreenSharing)
                .footer(Text("ios.settings.showInScreenSharing.desc"))
        }
    }

    // MARK: - Support

    private var supportSection: some View {
        Section {
            NavigationLink {
                GettingStartedView()
            } label: {
                Label {
                    Text("ios.settings.gettingStarted")
                } icon: {
                    Image(systemName: "book")
                }
            }

            NavigationLink {
                HelpCenterView()
            } label: {
                Label {
                    Text("ios.settings.helpCenter")
                } icon: {
                    Image(systemName: "questionmark.circle")
                }
            }

            Button {
                contactSupport()
            } label: {
                Label {
                    Text("about.contactSupport")
                        .foregroundStyle(Color(UIColor.label))
                } icon: {
                    Image(systemName: "envelope")
                }
            }
        }
    }

    // MARK: - Legal

    private var legalSection: some View {
        Section {
            NavigationLink {
                PolicyView(document: .privacyPolicy)
            } label: {
                Text("about.privacyPolicy")
            }

            NavigationLink {
                PolicyView(document: .termsOfUse)
            } label: {
                Text("about.termsOfUse")
            }
        }
    }

    private func contactSupport() {
        let subject = String(localized: "ios.support.emailSubject")
        let body = String(localized: "ios.support.emailBody")
        var components = URLComponents()
        components.scheme = "mailto"
        components.path = "gxlself@gmail.com"
        components.queryItems = [
            URLQueryItem(name: "subject", value: subject),
            URLQueryItem(name: "body", value: body),
        ]
        if let url = components.url {
            UIApplication.shared.open(url)
        }
    }

    // MARK: - Action extension detail

    private var actionExtensionDetail: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 8) {
                    Text("ios.extension.howToUse")
                        .font(.headline)
                    Text("ios.extension.step1")
                    Text("ios.extension.step2")
                    Text("ios.extension.step3")
                }
                .font(.subheadline)
                .padding(.vertical, 4)
            }
        }
        .navigationTitle(Text("preferences.general.integration"))
        .navigationBarTitleDisplayMode(.inline)
    }

    // MARK: - Keyboard settings detail

    private var keyboardSettingsDetail: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 8) {
                    Text("ios.keyboard.howToEnable")
                        .font(.headline)
                    Text("ios.keyboard.step1")
                    Text("ios.keyboard.step2")
                    Text("ios.keyboard.step3")
                    Text("ios.keyboard.step4")
                }
                .font(.subheadline)
                .padding(.vertical, 4)
            }

            Section {
                Button(String(localized: "preferences.general.accessibility.openSettings")) {
                    if let url = URL(string: UIApplication.openSettingsURLString) {
                        UIApplication.shared.open(url)
                    }
                }
            }
        }
        .navigationTitle(Text("preferences.tab.shortcuts"))
        .navigationBarTitleDisplayMode(.inline)
    }
}

// MARK: - Settings Icon

private struct SettingsIcon: View {
    let systemName: String
    let color: Color

    var body: some View {
        Image(systemName: systemName)
            .font(.system(size: 14, weight: .medium))
            .foregroundColor(.white)
            .frame(width: 28, height: 28)
            .background(color, in: RoundedRectangle(cornerRadius: 6, style: .continuous))
    }
}

// MARK: - Toggle footer

extension Toggle {
    func footer(_ text: Text) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            self
            text
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }
}
